// <auto-generated />
namespace project_sem_3_api.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class fixorderIdtype : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fixorderIdtype));
        
        string IMigrationMetadata.Id
        {
            get { return "202006300338051_fix orderId type"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
