// <auto-generated />
namespace project_sem_3_api.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class fix_model_ticket : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fix_model_ticket));
        
        string IMigrationMetadata.Id
        {
            get { return "202006290457574_fix_model_ticket"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
