// <auto-generated />
namespace project_sem_3_api.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class changeidorderontabletiketstolong : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changeidorderontabletiketstolong));
        
        string IMigrationMetadata.Id
        {
            get { return "202007031029412_change id order on table tikets to long"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
